<a href="https://colab.research.google.com/github/vishnudevireddy39/vishnudevireddy39/blob/main/Goeduhub_task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

GO_STP_12120
Task 4
Vishnu vardhan

Vignan's Lara Institute of Technology and Science

In [2]:
#1.Printing Version of numpy
import numpy as np
print(np.__version__)

1.19.5


In [3]:
#2.Vector is also known as 1D array
l=[10,20,30]
arr=np.array(l)
print("The Vector is: ",arr)

The Vector is:  [10 20 30]


In [5]:
#3.creating 1D array and checking type of array and datatypes in array
l=[10,30,20,40]
arr=np.array(l)
print(type(arr))
for i in arr:
  print("the element ",i,"type is ",type(i))

<class 'numpy.ndarray'>
the element  10 type is  <class 'numpy.int64'>
the element  30 type is  <class 'numpy.int64'>
the element  20 type is  <class 'numpy.int64'>
the element  40 type is  <class 'numpy.int64'>


In [10]:
#4.finding no.of dimensions,bytes per element and bytes used by array
arr=np.array([[10,20,30],[40,50,60]])
print("dimensions of an array:",arr.ndim)
print("memory size per element:",arr.itemsize)
print("memory used by array:",arr.size*arr.itemsize)

dimensions of an array: 2
memory size per element: 8
memory used by array: 48


In [11]:
#5.create null vector of size 10 and fifth element is 1
a = np.zeros((10))
print(a)
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#6.creating a vector ranges from 10 to 49
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#7.Reverse a vector 
arr=np.arange(1,20,3)
print(arr[::-1])

[19 16 13 10  7  4  1]


In [14]:
#8. 3x3 matrix ranges from 0 to 8
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#9.Find indices of non zero elements [1,2,0,0,4,0]
a = np.array([1,2,0,0,4])
ar =a.nonzero()
print(ar)

(array([0, 1, 4]),)


In [16]:
#10.create 3x3 identity matrix
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#11.create a 3x3x3 array with random values
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [19]:
#12.create 10x10 array with random values and find min and max
arr=np.random.randint(1000,size=(10,10))
print(arr)
print(arr.min()," is the minimum value")
print(arr.max()," is the maximum value")

[[317 140 503 820 130 720 575 607 169   5]
 [421  70 101 774 351 521   0 304 881 340]
 [ 24 531 642 559 961 950 271 718  29 572]
 [685 475 348 565  44 450 595 758  97 900]
 [432 748 413 729 733 540 863 153 755  79]
 [332 896 754 203 522 770 433 478 719 734]
 [631 700 113 875 577 699  98  24  70  95]
 [410 305 446 487   2 272 599 929 952 300]
 [965 711 717 865 250 868 466 742  25 889]
 [920 556 582 176 894 952 554 956 319 778]]
0  is the minimum value
965  is the maximum value


In [20]:
#13.create a random vector of size 30 and find mean value
arr=np.random.randint(1000,size=30)
print(arr)
print("The mean is ",arr.mean())

[762 518 269 170 770 159 689 912 961 854 626 273 194 273 471 798 838 432
 380 425 982 995 634 793 258 248 245 807 509 135]
The mean is  546.0


In [21]:
#14.create a 2D array with borders ones and inside zeroes
arr=np.ones((7,7),dtype=int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [22]:
#15.add a border filled with zeroes in a 2D array
arr=np.ones((6,6),dtype=int)
print(arr)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [23]:
print(arr.shape)
arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(arr)
print(arr.shape)

(6, 6)
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
(8, 8)


In [24]:
#16.accessing,modifying elements in a 2D array

a = np.array([[ 1 ,2 ,3, 4, 5, 6 ,7],[ 8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.ndim)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2


In [25]:
print(a[1][2:])

[10 11 12 13 14]


In [26]:
print(a[0])

[1 2 3 4 5 6 7]


In [27]:
a[1][3]=34
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 34 12 13 14]]
